homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 0
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include customize.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Enables support for tracking state changes over time
history:

# Tracked history is kept for 10 days
recorder:
  purge_keep_days: 10

# View all events in a logbook
logbook:

# MQTT Broker
mqtt:
  broker: localhost
  username: !secret mqtt_username
  password: !secret mqtt_password

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: buienradar
    name: Outdoor
    monitored_conditions:
      - symbol
      - humidity
      - temperature
      - windspeed
      - pressure

# Cloud
cloud:

# Zone defenition
zone:
  - name: Home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    radius: 250

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

light: !include lights.yaml
